Subscribe by Id (Evaluation)
eclipse-velocitas/vehicle-app-cpp-sdk pull request #115
Opened 2024-12-07 09:47 UTC by BjoernAtBosch

## Describe your changes

This implements subscribing to signals via the numeric id. This is implemented on top of the custum channel arguments PR.
Steps during subscribe:
- Fetch metadata for each signal to be subscribed and which is net yet cached in the MetadataStore.
  This is done in an asynchronous loop for each signal separately - due to limitations of the `ListMetadata` request of the broker.
  The return metadata (currently just path and id) is added to the MetadataStore.
- Finally call `subscribeById` request using the cached ids.

## Issue ticket number and link

## Checklist - Manual tasks

* [ ] Examples are executing successfully
* [ ] Created/updated unit tests. Code Coverage percentage on new code shall be >= 80%.
* [ ] Created/updated integration tests.

* [ ] Devcontainer can be opened successfully
* [ ] Devcontainer can be opened successfully behind a corporate proxy
* [ ] Devcontainer can be re-built successfully

* [ ] Extended the documentation (e.g. README.md, CONTRIBUTING.md, Velocitas Docs)

2025-01-15 07:55 UTC, lukasmittag commented
what happens if databroker restarts and the ids of the paths change? Will a client application written with this code see this and can act on it?

2025-01-15 11:41 UTC, MP91 requested changes

2025-01-15 11:54 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerAsyncGrpcFacade.h
> +    }
Yes, because it's a template. But this was a yet unused tryout, that I will remove from the PR.

2025-01-15 12:05 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +            onMetadataError(grpc::Status(grpc::StatusCode::NOT_FOUND, ""));
Depends on the compiler flags: I think, the assert is only done in debug build where crashes caused by asserts quickly point to code issues.
In release builds a crash wouldn't be acceptable, so the error is given instead. I'll refactor this.

2025-01-15 12:09 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +            m_currentPath = m_signalPaths.cend();
All errors not given in the if statement ;-)
I added a comment motivating the else branch

2025-01-15 12:14 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +}
It's a small optimization: The `static` ensures that `determineSubscribeBufferSize` is just called once when `getSubscribeBufferSize` is called for the first time. Afterwards just the value of `bufferSize`is returned.

2025-01-15 12:15 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +// Please check for better solution before merging to main!
:->

2025-01-15 12:23 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +            onMetadataError(grpc::Status(grpc::StatusCode::NOT_FOUND, ""));
Also, in case of more than one metadata received it wrong to assume, that the first one is the metadata of the requested signal. So, I'll set the signal to unknown in those cases, too.

2025-01-15 12:53 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +                       bufferSize);
The default is explained in the proto file. I modified the code a bit. Hoping it's clearer then.

2025-01-15 13:02 UTC, BjoernAtBosch commented
> what happens if databroker restarts and the ids of the paths change? Will a client application written with this code see this and could act on it?

Whenever an ongoing subscribeById call is terminated with a status code `UNAVAILABLE` or `OK`, the stored metadata is invalidated and fetched again before re-subscribing.
I'm not 100% if there could be other constellations when to invalidate metadata. I also thought, that the broker could offer some kind of "session id" which is altered each time the broker restarts. With that it would be easier to determine the necessity to request metadata again.

2025-01-15 13:06 UTC, MP91 commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +}
ah interesting, missed the static

2025-01-15 13:17 UTC, MP91 commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +            assert(response.metadata_size() == 1);
isn't that assert now always triggered? size in the else branch should always be != 1

2025-01-15 13:51 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +            assert(response.metadata_size() == 1);
assert removed - error case is sufficiently handled by the else case

2025-01-15 13:55 UTC, rafaeling reviewed
LGTM

2025-01-15 13:55 UTC, rafaeling commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +        case grpc::StatusCode::OK:
If status is Ok on error nothing should be done?

2025-01-15 14:07 UTC, MP91 commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +        case grpc::StatusCode::OK:
good catch, since this is actually the onFinish-Handler in the subcribeById call, I wonder if a subscription is finished and status is ok, do we really want to resubscribe?

2025-01-15 14:52 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +        if (response.metadata_size() != 0) {
I removed this due to discussion with Markus.

2025-01-15 14:59 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +        case grpc::StatusCode::OK:
The databroker should never terminate existing subscriptions - except in error cases. Means, from consumer perspective a subscription should live as long as the consumer is not cancelling it. If a subscription is terminated by the broker side this is always an error situation for the consumer.
Currently, the databroker sends an `OK` if it is terminated by SIGINT. But actually it should send an `UNAVAILABLE`.

2025-01-15 15:26 UTC, BjoernAtBosch commented on sdk/src/sdk/vdb/grpc/kuksa_val_v2/BrokerClient.cpp
> +        case grpc::StatusCode::OK:
(Sending the `OK` from provider/server side makes sense in case where something finite is streamed, e.g. a file or a movie. When the end is reached the provider sends the ok to signal that all data has been send. In the databroker case, there is no end - another update of a signal can come in at any time.)

2025-01-16 07:22 UTC, MP91 approved these changes
lgtm

2025-01-16 07:22 UTC, merged